name: Docker build 

on:
  push:

jobs:
  build_login:
     uses: ./.github/workflows/reuse.yml
     secrets: 
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

      

    
  
