name: Docker build 

on:
  push:

jobs:
  build_login:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: install dependencies
      run: npm install

    - name: test
      run: npm test

    - name: docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

      

    
  
