name: Function app deployment

on:
  push:

env:
  AZURE_FUNCTIONAPP_NAME: 'Actions-11'                     # Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                     # Path to function app code

jobs:
  upload_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Upload test result file (already in repo)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
          if-no-files-found: error                         

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
