name: Function app deployment

on:
  push:


env:
  AZURE_FUNCTIONAPP_NAME: 'Actions-11'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4.2.2

    - name: Dependencies install
      run: npm install

    - name: Test code
      run: npm test

  upload_download:
    runs-on: ubuntu-latest

    steps:

    - name: chekout repo
      uses: actions/checkout@v4.2.2
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name:  my-artifact
        path: test-results.xml
        
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: test-results.xml
    - name: Display structure of downloaded files
      run: ls -R

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      

        
 

    

    
      
