name: Reusable workflow

on:
  workflow_call:
    inputs:
      version: 
        type: number
        required: false
        default: 18
    
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.username }}
          password:
