name: Reusable workflow

on:
  workflow_call:
    inputs:
      node-version: 
        default: 18
        required: false
        type: number
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: setup node
      uses: actions/setup-node@v4
      with:
       node-version: 18

    - name: install dependencies
      run: npm install
     

    - name: test
      run: npm test

    - name: docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }} 


  
    
    
