name: Unit testing workflow

on:
  push:
  
jobs:
  Unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Node.js with version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Archive/store
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test-results.xml
     

  upload:
    needs: Unit-testing
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v4
        
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
